name: Build Android CI

on: [push]

jobs:
  ktlint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Ktlint
        run: ./gradlew ktlintCheck
      - name: Upload Ktlint Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ktlint-report
          path: shared/build/reports/
          retention-days: 1

  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Tests
        run: ./gradlew shared:testDebugUnitTest
      - name: Upload Test Summary
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-summary
          path: shared/build/reports/
          retention-days: 1
